"""Fix sequence field type mismatch

Revision ID: 2024_12_05_fix_sequence
Revises: 3be29583703d
Create Date: 2024-12-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2024_12_05_fix_sequence'
down_revision = '3be29583703d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
                    existing_type=sa.Integer(),
                    type_=sa.Float(precision=3),
                    existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
                    existing_type=sa.Float(precision=3),
                    type_=sa.Integer(),
                    existing_nullable=True)

    # ### end Alembic commands ###
