"""Fix theme colors relationship

Revision ID: 726c05a3e6a9
Revises: 3b64ecbfd0f6
Create Date: 2024-12-10 22:08:17.869323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726c05a3e6a9'
down_revision = '3b64ecbfd0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
