"""Fix theme colors relationship

Revision ID: a9ba79da5a62
Revises: 55630ec4e8e3
Create Date: 2024-12-10 16:28:40.859168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ba79da5a62'
down_revision = '55630ec4e8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)

    with op.batch_alter_table('theme_colors', schema=None) as batch_op:
        batch_op.drop_constraint('theme_colors_theme_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'theme', ['theme_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_colors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('theme_colors_theme_id_fkey', 'theme', ['theme_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
