"""Add theme management tables

Revision ID: c7de625e87eb
Revises: a925dc19aad9
Create Date: 2024-12-10 08:33:51.893018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7de625e87eb'
down_revision = 'a925dc19aad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('columns_per_row',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
        batch_op.drop_column('category_sequence')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_sequence', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.alter_column('columns_per_row',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))

    # ### end Alembic commands ###
